steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/test-34621369/github.com/fmoralvi/mlops:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/test-34621369/github.com/fmoralvi/mlops:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'test-34621369', '--image=gcr.io/test-34621369/github.com/fmoralvi/mlops:$SHORT_SHA', '--region=europe-west1', '--platform=managed']
